# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convex NMF for mix-signed matricies using ADMM
#'
#' This function implements a ADMM for NMF taking a single matrix
#' of any shape and potentially mix-signed.
#' X~XWG with W & G non-negative.
#'
#' @param V         A (m x n) vector of data matrix with m features and n units
#' @param k         An integer to specify desired rank of the low rank factorization result
#' @param cluster   A (k x 1) vector of integer 0~(k-1) indicating initial cluster assignment
#' @param verbose   A 0/1 integer (default 0). If 1: output the relative error after each iteration
#' @param maxiter   An integer (default 100) for the maximal number of iterations
#' @param fixediter An integer (optional) for a fixed number of iterations
#' @param rho       Penalty parameter in ADMM (default 3)
#' @param tol       Tolerance parameter to declare convergence
#' @return A list containing the following values
#' * W     : A (n x k) non-negative matrix containing W in X~XWG
#' * G     : A (k x n) non-negative matrix containing G in X~XWG
#' * Error : A vector containing the relative distance of this approximation in each iteration
#' @export
ConvexNMF_ADMM <- function(V, k, cluster, verbose = 0L, maxiter = 100L, fixediter = 0L, rho = 3, tol = 1e-3) {
    .Call(`_nmfADMM_ConvexNMF_ADMM`, V, k, cluster, verbose, maxiter, fixediter, rho, tol)
}

#' Joint symmetric NMF for multiple input matricies using ADMM
#'
#' This function implements a ADMM for NMF taking two n x n matrices.
#' (One of them presumably measures similarity and symmetric)
#' V := Vp - Vm ~ W1G^t + W2G^t with Vp, Vm, W1, W2 & G non-negative.
#'
#' @param Vp        A (n x n) non-negative matrix measuring similariy
#' @param Vm        A (n x n) non-negative matrix containing the abs value of the negative part
#'                  in the original data matrix.
#' @param k         An integer to specify desired rank of the low rank factorization result
#' @param cluster   A (k x 1) vector of integer 0~(k-1) indicating initial cluster assignment
#' @param dist      A string indicating the distance measure (default: "F2").
#' Currently only "F2", for Euclidean distance and "KL" for KL divergence are implemented
#' @param verbose   A 0/1 integer (default 0). If 1: output the relative error after each iteration
#' @param maxiter   An integer (default 100) for the maximal number of iterations
#' @param fixediter An integer (optional) for a fixed number of iterations
#' @param rho       Penalty parameter in ADMM (default 3)
#' @param tol       Tolerance parameter to declare convergence
#' @return A list containing the following values
#' * W1     : A (n x k) non-negative matrix containing W1 in Vp ~ W1G^t
#' * W2     : A (n x k) non-negative matrix containing W2 in Vm ~ W1G^t
#' * G      : A (n x k) non-negative matrix containing G in V ~ W1G^t + W2G^t
#' * Error  : A vector containing the relative distance of this approximation in each iteration
#' @export
SymNMFs_ADMM <- function(Vp, Vm, k, cluster, dist = "F2", verbose = 0L, maxiter = 100L, fixediter = 0L, rho = 3, tol = 1e-3) {
    .Call(`_nmfADMM_SymNMFs_ADMM`, Vp, Vm, k, cluster, dist, verbose, maxiter, fixediter, rho, tol)
}

#' Symmetric NMF for one non-negative symmetric matrix using ADMM
#'
#' This function implements a ADMM for NMF taking a non-negative square matrix
#' presumably measuring similarity
#' V ~ WG^t with V, W & G non-negative.
#'
#' @param V         A (n x n) non-negative symmetric matrix
#' @param k         An integer to specify desired rank of the low rank factorization result
#' @param cluster   A (k x 1) vector of integer 0~(k-1) indicating initial cluster assignment
#' @param dist      A string indicating the distance measure (default: "F2").
#' Currently only "F2", for Euclidean distance and "KL" for KL divergence are implemented
#' @param verbose   A 0/1 integer (default 0). If 1: output the relative error after each iteration
#' @param maxiter   An integer (default 100) for the maximal number of iterations
#' @param fixediter An integer (optional) for a fixed number of iterations
#' @param rho       Penalty parameter in ADMM (default 3)
#' @param tol       Tolerance parameter to declare convergence
#' @return A list containing the following values
#' * W      : A (n x k) non-negative matrix containing W in V ~ WG^t
#' * G      : A (n x k) non-negative matrix containing G in V ~ WG^t
#' * Error  : A vector containing the relative distance of this approximation in each iteration
#' @export
SymNMF_ADMM <- function(V, k, cluster, dist = "F2", verbose = 0L, maxiter = 100L, fixediter = 0L, rho = 3, tol = 1e-3) {
    .Call(`_nmfADMM_SymNMF_ADMM`, V, k, cluster, dist, verbose, maxiter, fixediter, rho, tol)
}

